os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swift.vapor.sh/ubuntu)"; fi

  # run unit tests
  - swift build -Xswiftc -DNO_ANIMATION
  - swift build --configuration release -Xswiftc -DNO_ANIMATION
  - swift test

  - .build/release/Executable self install

  - vapor --help
  - vapor version                   # version

  # docker
  - rm Dockerfile                   # docker init won't run if file exists
  - vapor docker init -n

  # basic
  - vapor new test-project          # new
  - cd test-project
  - vapor fetch                     # fetch
  - vapor clean                     # clean
  - vapor build                     # build
  - vapor run &                     # run

  - vapor self update

