os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swiftenv install 3.0.1 || echo ""
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL swift.vapor.sh/ubuntu | bash; fi

  # run unit tests
  - swift build -Xswiftc -DNO_ANIMATION
  - swift build --configuration release -Xswiftc -DNO_ANIMATION
  - swift test

  - .build/release/Executable self install

  - vapor --help
  - vapor version                   # version

  # docker
  - rm Dockerfile                   # docker init won't run if file exists
  - vapor docker init -n

  # basic
  - vapor new test-project          # new
  - cd test-project
  - vapor fetch                     # fetch
  - vapor clean                     # clean
  - vapor build                     # build
  - vapor run &                     # run

  - vapor self update

