name: test
on:
- pull_request
jobs:
  toolbox_macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --enable-test-discovery --sanitize=thread   
  toolbox_xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift build --enable-test-discovery --sanitize=thread
  toolbox_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift build --enable-test-discovery --sanitize=thread
